Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "gusztavvargadr/ubuntu-server"
    master.vm.hostname = "srvDHCPvagrant"
    master.vm.network "public_network", bridge: "enp2s0"
    master.vm.network "private_network", ip: "192.168.100.1", virtualbox__intnet: "DHCP1"
    master.vm.network "private_network", ip: "192.168.200.1", virtualbox__intnet: "DHCP2"
    master.vm.network "private_network", ip: "192.168.30.1", virtualbox__intnet: "DHCP3"
 end
  config.vm.define "slave" do |slave|
    slave.vm.box = "gusztavvargadr/ubuntu-server"
    slave.vm.hostname = "srvDHCPFAILOVERvagrant"
    slave.vm.network "public_network", bridge: "enp2s0"
    slave.vm.network "private_network", ip: "192.168.100.2", virtualbox__intnet: "DHCP1"
  end
end
